### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by antithing** [pmbittner/OptimisedCentresOfRotationSkinning#1]
Hi, thanks for making this code available!

Can you please post steps to use this code?

Eg, I have a rigged fbx character, how do I apply this skinning and then export the skinned skeleton mesh? 

Thanks!

**Comment by pmbittner** [comment]
Dear @antithing ,

sorry for the late response. This repository contains material of my bachelor's thesis and I am not working on this project anymore. The code contains some examples but you still have to write your own code and figure out how to combine the skinning with your rendering engine and data formats. ;) This repository serves as a reference and example but not as a ready-to-use library.

Kind regards
Paul
